---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./
    enforce_order: True
  dnsimple:
    class: octodns.provider.dnsimple.DnsimpleProvider
    token: env/DNSIMPLE_API_KEY
    account: env/DNSIMPLE_ACCOUNT_NUMBER
    delete_pcent_threshold: 1.0

zones:
  hackclub.com.:
    sources:
      - config
    targets:
      - dnsimple
  hackclub.org.:
    sources:
      - config
    targets:
      - dnsimple
  hackclub.io.:
    sources:
      - config
    targets:
      - dnsimple
  hackedu.us.:
    sources:
      - config
    targets:
      - dnsimple
  hack.af.:
    sources:
      - config
    targets:
      - dnsimple
  bulckcah.com.:
    sources:
      - config
    targets:
      - dnsimple
  dino.icu.:
    sources:
      - config
    targets:
      - dnsimple
  dinosaurbbq.org.:
    sources:
      - config
    targets:
      - dnsimple
  hack.club.:
    sources:
      - config
    targets:
      - dnsimple
  hackclub.app.:
    lenient: true
    sources:
      - config
    targets:
      - dnsimple
  hackfoundation.org.:
    sources:
      - config
    targets:
      - dnsimple
  wackclub.com.:
    sources:
      - config
    targets:
      - dnsimple
  bank.engineering.:
    sources:
      - config
    targets:
      - dnsimple
  scrap.dev.:
    sources:
      - config
    targets:
      - dnsimple
  scrapbook.dev.:
    sources:
      - config
    targets:
      - dnsimple
  cpu.land.:
    sources:
      - config
    targets:
      - dnsimple
  aisafety.dance.:
    sources:
      - config
    targets:
      - dnsimple
  nonprofit.new.:
    sources:
      - config
    targets:
      - dnsimple
